services:

    # _____ _   _ _____ 
    #|  __ \ | | |_   _|
    #| |  \/ | | | | |  
    #| | __| | | | | |  
    #| |_\ \ |_| |_| |_ 
    # \____/\___/ \___/ 

    # GUI Section

    gui:
        image: ${BASE_IMAGE_LOCATION}/${PROJECT_NAME}-gui:${BACKEND_VERSION}
        networks:
            - traefik-public
            - euler-dev
    
    # _____                                         
    #|  __ \                                        
    #| |  \/ ___  ___  ___  ___ _ ____   _____ _ __ 
    #| | __ / _ \/ _ \/ __|/ _ \ '__\ \ / / _ \ '__|
    #| |_\ \  __/ (_) \__ \  __/ |   \ V /  __/ |   
    # \____/\___|\___/|___/\___|_|    \_/ \___|_|   
                                               
    # Geoserver Section                                           

    geoserver:
        image: ${BASE_IMAGE_LOCATION}/${PROJECT_NAME}-geoserver:${BACKEND_VERSION}
        deploy:
            labels:
                traefik.enable: "true"
                traefik.http.routers.geoserver-http.entrypoints: https
                traefik.http.routers.geoserver-http.rule: Host(`geoserver.${DEPLOY_DOMAIN}`)
                traefik.http.routers.geoserver-http.tls: "true"
                traefik.http.routers.geoserver-http.tls.certresolver: georesolver
                traefik.http.services.geoserver.loadbalancer.server.port: "8080"
        environment:
            GEOSERVER_ADMIN_USER: kartoza
            GEOSERVER_ADMIN_PASSWORD: password
            PROXY_BASE_URL: https://geoserver.${DEPLOY_DOMAIN}/geoserver
            GEOSERVER_CSRF_DISABLED: "true"
        volumes:
            - ${NFS_SHARED_DOCKERDATA}/geoserver/data:/opt/geoserver/data_dir
        networks:
            - traefik-public
            - euler-dev

    #______          _    ___  ______ _____ 
    #| ___ \        | |  / _ \ | ___ \_   _|
    #| |_/ /___  ___| |_/ /_\ \| |_/ / | |  
    #|    // _ \/ __| __|  _  ||  __/  | |  
    #| |\ \  __/\__ \ |_| | | || |    _| |_ 
    #\_| \_\___||___/\__\_| |_/\_|    \___/ 

    # RestAPI Section                                 

    restapi:
        image: ${BASE_IMAGE_LOCATION}/${PROJECT_NAME}-restapi:${BACKEND_VERSION}
        networks:
        - traefik-public
        - euler-dev


    #____________ 
    #|  _  \ ___ \
    #| | | | |_/ /
    #| | | | ___ \
    #| |/ /| |_/ /
    #|___/ \____/ 

    # Database Section

    db-ps:
        image: ${BASE_IMAGE_LOCATION}/${PROJECT_NAME}-db:${BACKEND_VERSION}
        ports:
            - 5432:5432
        environment:
            PGDATA: /var/lib/postgresql/data/pgdata
            POSTGRES_SERVER: euler
            POSTGRES_DB: EULER
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_passwd
            DB_HOSTNAME: cots-db
            DB_PORT: 5432
            DB_DATABASE: euler
            DB_USERNAME: euler
            DB_PASSWORD_FILE: /run/secrets/postgres_passwd
            PROJECT_PASSWORD_FILE: /run/secrets/postgres_passwd
            PROJECT_USER: euler
        volumes:
            - ${NFS_SHARED_DOCKERDATA}/postgres/db:/var/lib/postgresql/data:rw
        secrets:
            - postgres_passwd
        networks:
            - euler-dev

networks:
    euler-dev:
        external: true
    traefik-public:
        external: true
secrets:
    postgres_passwd:
       external: true
       name: postgres_passwd
