FROM dockerhub.euler.it/stagionality_ps-import_ps_base:develop

WORKDIR /usr/local/rheticus_import_ps/src/build/libs

CMD java -Xms2g -Xmx8g -jar import-spinua-ps-0.0.1-SNAPSHOT.jar --spring.config.additional-location=/usr/local/rheticus_import_ps_config/